version: '3.3'
services:
  postgres:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_PASSWORD=bbookPw
  postgres-test-init:
    image: postgres:9.6
    restart: always
    volumes:
      - ./bin:/db-init
    working_dir: /db-init
    command: sh -c "sleep 5 && ./init-db.sh"
    depends_on:
      - postgres
    restart: "no"
  bbook-node-test:
    build:
      context: .
      dockerfile: test.Dockerfile
    volumes:
      - .:/bbook-app
    depends_on:
      - postgres
      - postgres-test-init
    command: sh -c "sleep 1 && yarn && yarn test"
