version: '3.3'
services:
  postgres:
    image: postgres:11.4
    restart: always
    ports:
      - "55432:5432"
  postgres-test-init:
    image: postgres:11.4
    restart: always
    volumes:
      - ./bin:/db-init
    working_dir: /db-init
    command: sh -c "sleep 5 && ./init-db.sh"
    depends_on:
      - postgres
    restart: "no"
