version: '3.3'
services:
  postgres:
    image: postgres:9.6.14
    restart: always
    volumes:
      - ./.tmp/postgres/data:/var/lib/postgresql/data 
    environment:
      - POSTGRES_PASSWORD=bbookPw
  postgres-init:
    image: postgres:9.6.14
    restart: always
    volumes:
      - ./.tmp/postgres/data:/var/lib/postgresql/data 
      - ./bin:/db-init
    working_dir: /db-init
    command: sh -c "sleep 5 && ./init-db.sh"
    depends_on:
      - postgres
